version: '3.8'

services:
  ecommerce:
    build:
      context: ./ecommerce
    ports:
      - '3000:3000'
    networks:
      - my-network

  bff-ecommerce:
    build:
      context: ./bff-ecommerce
    ports:
      - '8080:8080'
    networks:
      - my-network

  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - ecommerce
      - bff-ecommerce
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
